name: Run Sys/Info.js Script

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Sys/Info.js script
        run: node Sys/Info.js
